# Generated by Django 4.1.2 on 2022-11-02 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0002_rental_created_rental_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="rental",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="rental",
            name="car_model",
            field=models.CharField(
                choices=[
                    ("Tesla Malibu", "Tesla Malibu"),
                    ("Toyota Aventador", "Toyota Aventador"),
                    ("BMWX3", "BMWX3"),
                    ("Nissan Mercielago", "Nissan Mercielago"),
                    ("Ferrari Camry", "Ferrari Camry"),
                    ("Mercedes Benz XC90", "Mercedes Benz XC90"),
                ],
                max_length=100,
            ),
        ),
    ]
