# Generated by Django 4.1.2 on 2022-11-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0003_rental_email_alter_rental_car_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rental",
            name="email",
        ),
    ]
