# Generated by Django 4.1.2 on 2022-11-21 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0007_email_message_email_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 21, 15, 49, 11, 84085, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
