# Generated by Django 4.1.2 on 2022-11-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="paid",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
