# Generated by Django 4.1.2 on 2022-11-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
