# Generated by Django 4.1.2 on 2022-11-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_price_alter_trip_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
